"use strict";
exports.__esModule = true;
var a = 40;
var b = "kumar";
var c = "ravi singh";
var d = 8000;
var f = "kumar";
var x = [];
var y = [10, 20, 30, 20, 450, 50];
var u = ["kumar", "ravi", "mohan"];
var p = [10, 20, 30, "kumar", "oooo", "abc"];
var w = [40, "kumar", true, "ravi"];
console.log(d);
console.log(typeof (d));
exports["default"] = a;
